[tool.poetry]
name = "docat"
version = "0.0.0"
description = "Host your docs. Simple. Versioned. Fancy."
authors = ["Felix <hi@l33t.name>", "Benj <randombenj@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6"
flask = "*"

[tool.poetry.dev-dependencies]
flake8 = "*"
flake8-isort = "*"
flake8-black = "*"
pytest = "*"
pytest-cov = "*"
mock = "*"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--ff -ra -v"
testpaths = [
    "tests",
    "docat",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 140

[tool.black]
line-length = 140